DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM "SecurityEvent"
    WHERE type::text IN (
      'TWO_FACTOR_SETUP_STARTED',
      'TWO_FACTOR_CHALLENGE_FAILED',
      'TWO_FACTOR_CHALLENGE_COMPLETED',
      'RECOVERY_CODE_LOGIN_SUCCEEDED',
      'RECOVERY_CODE_LOGIN_FAILED'
    )
  ) THEN
    RAISE EXCEPTION 'PHASE6D_ROLLBACK: restore the pre-migration backup; Phase 6D security events exist';
  END IF;
END $$;

DROP INDEX IF EXISTS "TwoFactorChallenge_userId_sessionVersion_expiresAt_idx";
ALTER TABLE "TwoFactorChallenge" DROP CONSTRAINT IF EXISTS "TwoFactorChallenge_session_version_check";
ALTER TABLE "TwoFactorChallenge" DROP COLUMN IF EXISTS "sessionVersion";

ALTER TYPE "SecurityEventType" RENAME TO "SecurityEventType_phase6d";
CREATE TYPE "SecurityEventType" AS ENUM (
  'REGISTRATION','VERIFICATION_REQUESTED','EMAIL_VERIFIED','LOGIN_SUCCEEDED','LOGIN_FAILED',
  'TWO_FACTOR_CHALLENGE','TWO_FACTOR_ENABLED','RECOVERY_CODE_USED','TWO_FACTOR_DISABLED',
  'PASSWORD_RESET_REQUESTED','PASSWORD_RESET_COMPLETED','PASSWORD_CHANGED','PASSWORD_CHANGE_FAILED',
  'SESSIONS_INVALIDATED','ACCOUNT_DISABLED','SESSION_VERSION_INITIALIZED','SESSION_VERSION_INCREMENTED',
  'PASSWORD_RESET_TOKEN_CREATED','PASSWORD_RESET_TOKEN_CONSUMED','PASSWORD_RESET_TOKENS_INVALIDATED',
  'TOTP_CONFIGURATION_CREATED','TOTP_STEP_REPLAY_REJECTED','TWO_FACTOR_CHALLENGE_CREATED',
  'TWO_FACTOR_CHALLENGE_CONSUMED','TWO_FACTOR_CHALLENGE_INVALIDATED','RECOVERY_CODE_CONSUMED',
  'RECOVERY_CODES_REGENERATED'
);
ALTER TABLE "SecurityEvent" ALTER COLUMN type TYPE "SecurityEventType" USING type::text::"SecurityEventType";
DROP TYPE "SecurityEventType_phase6d";
