import { CreateInmobiliariaForm } from '@/components/admin/CreateInmobiliariaForm';
import { redirect } from 'next/navigation';
import { AdminInviteAgentForm } from '@/components/admin/AdminInviteAgentForm';
import { prisma } from '@/lib/prisma';
import { requireGlobalAdmin } from '@/lib/panel-authorization';

export const metadata = { title: 'Inmobiliarias | Administración' };

export default async function AdminInmobiliariasPage() {
  await requireGlobalAdmin().catch(() => redirect('/?error=unauthorized'));
  const tenants = await prisma.inmobiliaria.findMany({ orderBy: { createdAt: 'desc' }, take: 100, select: { id: true, nombreAgencia: true, cuit: true, direccion: true, createdAt: true, user: { select: { nombre: true, email: true, activo: true, emailVerifiedAt: true } }, _count: { select: { agentes: true, propiedades: true } } } });
  return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-naranja-light">Administración</p><h1 className="mt-2 text-4xl font-semibold">Inmobiliarias</h1><p className="mt-2 text-white/65">Tenants y administradores de la plataforma.</p></header><div className="mt-8"><CreateInmobiliariaForm /></div><div className="mt-6"><AdminInviteAgentForm tenants={tenants.map(({ id, nombreAgencia }) => ({ id, nombreAgencia }))} /></div><section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/5 shadow-lg shadow-black/20"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-white/55"><tr><th className="px-5 py-4">Inmobiliaria</th><th className="px-5 py-4">Administrador</th><th className="px-5 py-4">Estado</th><th className="px-5 py-4">Relaciones</th><th className="px-5 py-4">Creada</th></tr></thead><tbody className="divide-y divide-white/10">{tenants.map((tenant) => <tr key={tenant.id}><td className="px-5 py-4"><strong className="block">{tenant.nombreAgencia}</strong><span className="text-white/55">{tenant.cuit} · {tenant.direccion}</span></td><td className="px-5 py-4"><span className="block">{tenant.user.nombre}</span><span className="text-white/55">{tenant.user.email}</span></td><td className="px-5 py-4">{tenant.user.activo ? tenant.user.emailVerifiedAt ? 'Activa' : 'Invitación pendiente' : 'Inactiva'}</td><td className="px-5 py-4">{tenant._count.agentes} agentes · {tenant._count.propiedades} publicaciones</td><td className="px-5 py-4 text-white/60">{tenant.createdAt.toLocaleDateString('es-AR')}</td></tr>)}</tbody></table></div></section></main>;
}
