DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM "AccountInvitation") OR EXISTS (
    SELECT 1 FROM "SecurityEvent"
    WHERE type::text IN (
      'GLOBAL_ADMIN_PROMOTED','INMOBILIARIA_CREATED','INMOBILIARIA_ADMIN_CREATED','AGENT_CREATED',
      'ACCOUNT_ACTIVATED','ACCOUNT_DEACTIVATED','ROLE_CHANGED','TENANT_ASSIGNMENT_CHANGED',
      'ACCOUNT_INVITATION_ACCEPTED'
    )
  ) THEN
    RAISE EXCEPTION 'PHASE7_ROLLBACK: restore the pre-migration backup; Phase 7 administrative data exists';
  END IF;
END $$;

DROP TABLE "AccountInvitation";
DROP INDEX "SecurityEvent_actorUserId_createdAt_idx";
DROP INDEX "SecurityEvent_targetUserId_createdAt_idx";
DROP INDEX "SecurityEvent_targetInmobiliariaId_createdAt_idx";
ALTER TABLE "SecurityEvent" DROP COLUMN "actorUserId", DROP COLUMN "targetUserId", DROP COLUMN "targetInmobiliariaId";

ALTER TYPE "SecurityEventType" RENAME TO "SecurityEventType_phase7";
CREATE TYPE "SecurityEventType" AS ENUM (
  'REGISTRATION','VERIFICATION_REQUESTED','EMAIL_VERIFIED','LOGIN_SUCCEEDED','LOGIN_FAILED',
  'TWO_FACTOR_CHALLENGE','TWO_FACTOR_ENABLED','RECOVERY_CODE_USED','TWO_FACTOR_DISABLED',
  'PASSWORD_RESET_REQUESTED','PASSWORD_RESET_COMPLETED','PASSWORD_CHANGED','PASSWORD_CHANGE_FAILED',
  'SESSIONS_INVALIDATED','ACCOUNT_DISABLED','SESSION_VERSION_INITIALIZED','SESSION_VERSION_INCREMENTED',
  'PASSWORD_RESET_TOKEN_CREATED','PASSWORD_RESET_TOKEN_CONSUMED','PASSWORD_RESET_TOKENS_INVALIDATED',
  'TOTP_CONFIGURATION_CREATED','TOTP_STEP_REPLAY_REJECTED','TWO_FACTOR_CHALLENGE_CREATED',
  'TWO_FACTOR_CHALLENGE_CONSUMED','TWO_FACTOR_CHALLENGE_INVALIDATED','RECOVERY_CODE_CONSUMED',
  'RECOVERY_CODES_REGENERATED','TWO_FACTOR_SETUP_STARTED','TWO_FACTOR_CHALLENGE_FAILED',
  'TWO_FACTOR_CHALLENGE_COMPLETED','RECOVERY_CODE_LOGIN_SUCCEEDED','RECOVERY_CODE_LOGIN_FAILED',
  'SESSION_CREATED','SESSION_REVOKED','OTHER_SESSIONS_REVOKED','ALL_SESSIONS_REVOKED','SESSION_EXPIRED'
);
ALTER TABLE "SecurityEvent" ALTER COLUMN type TYPE "SecurityEventType" USING type::text::"SecurityEventType";
DROP TYPE "SecurityEventType_phase7";
