import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';
import process from 'node:process';

const root=process.cwd();const migrationRoot=`${root}/database/migrations`;const phase7='20260805120000_phase7_global_administration';const integrationOnly=process.argv.includes('--integration-only');const container=`tandil-phase7-${process.pid}-${randomBytes(3).toString('hex')}`;
for(const argument of process.argv.slice(2))if(argument!=='--integration-only')throw new Error(`Argumento no reconocido: ${argument}`);
function run(command,args,options={}){const result=spawnSync(command,args,{cwd:root,encoding:'utf8',env:options.env??process.env,input:options.input,stdio:options.capture?['pipe','pipe','pipe']:['pipe','inherit','inherit']});if(!options.allowFailure&&result.status!==0)throw new Error(`${command} terminó con código ${result.status??'desconocido'}${result.stderr?`: ${result.stderr.trim()}`:''}`);return result;}
function docker(args,options={}){return run('docker',args,options);}function sql(database,input,options={}){return docker(['exec','-i',container,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres','-d',database],{input,capture:true,allowFailure:options.allowFailure});}function url(database,port){return `postgresql://postgres@127.0.0.1:${port}/${database}`;}function createDatabase(name){for(let attempt=0;attempt<30;attempt+=1){if(docker(['exec',container,'createdb','-U','postgres',name],{allowFailure:true,capture:true}).status===0)return;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,250);}throw new Error(`No se creó ${name}`);}function prisma(args,databaseUrl,options={}){return run('npx',['prisma',...args],{...options,env:{...process.env,DATABASE_URL:databaseUrl}});}function applyBeforePhase7(database){for(const name of readdirSync(migrationRoot,{withFileTypes:true}).filter((entry)=>entry.isDirectory()&&entry.name<phase7).map((entry)=>entry.name).sort())sql(database,readFileSync(`${migrationRoot}/${name}/migration.sql`,'utf8'));}
function integration(database,port){const databaseUrl=url(database,port);run('npx',['tsx','--test','tests/integration/phase-7-administration-postgres.test.ts'],{env:{...process.env,NODE_ENV:'test',DATABASE_URL:databaseUrl,PHASE7_DATABASE_URL:databaseUrl,NEXTAUTH_URL:'http://localhost:3000',NEXTAUTH_SECRET:randomBytes(48).toString('base64url'),APP_URL:'http://localhost:3000',AUTH_ENCRYPTION_KEY:randomBytes(32).toString('base64'),RATE_LIMIT_BACKEND:'memory'}});}
function empty(port){createDatabase('phase7_empty');const databaseUrl=url('phase7_empty',port);prisma(['migrate','deploy'],databaseUrl);const drift=prisma(['migrate','diff','--exit-code','--from-config-datasource','--to-schema','database/schema.prisma'],databaseUrl,{capture:true,allowFailure:true});if(drift.status!==0)throw new Error(`Drift Phase 7: ${drift.stdout}${drift.stderr}`);const structure=sql('phase7_empty',`SELECT count(*) FROM information_schema.tables WHERE table_name='AccountInvitation';
SELECT count(*) FROM pg_constraint WHERE conname IN ('AccountInvitation_userId_fkey','AccountInvitation_createdById_fkey','AccountInvitation_inmobiliariaId_fkey','AccountInvitation_expiry_check','AccountInvitation_state_check','AccountInvitation_role_check');
SELECT count(*) FROM pg_indexes WHERE indexname IN ('AccountInvitation_tokenHash_key','AccountInvitation_userId_consumedAt_invalidatedAt_expiresAt_idx','AccountInvitation_inmobiliariaId_intendedRole_createdAt_idx');
SELECT count(*) FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='SecurityEventType' AND e.enumlabel IN ('GLOBAL_ADMIN_PROMOTED','INMOBILIARIA_CREATED','INMOBILIARIA_ADMIN_CREATED','AGENT_CREATED','ACCOUNT_ACTIVATED','ACCOUNT_DEACTIVATED','ROLE_CHANGED','TENANT_ASSIGNMENT_CHANGED','ACCOUNT_INVITATION_ACCEPTED');`).stdout.trim();if(structure!=='1\n6\n3\n9')throw new Error(`Estructura Phase 7 inesperada: ${structure}`);integration('phase7_empty',port);process.stdout.write('phase7 empty: 23 migrations, constraints, integration and zero drift: ok\n');}
const fixture=`INSERT INTO "User" (id,rol,nombre,email,"passwordHash","twoFactorEnabled","twoFactorSecret","emailVerifiedAt",activo,"createdAt","updatedAt") VALUES
('phase7-owner-a','INMOBILIARIA','Owner A','owner-a@example.invalid','$2b$12$aaaaaaaaaaaaaaaaaaaaaaBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',false,NULL,CURRENT_TIMESTAMP,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('phase7-owner-b','INMOBILIARIA','Owner B','owner-b@example.invalid','$2b$12$ccccccccccccccccccccccDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',false,NULL,CURRENT_TIMESTAMP,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('phase7-agent-a','AGENTE','Agent A','agent-a@example.invalid','$2b$12$eeeeeeeeeeeeeeeeeeeeeeFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',false,NULL,CURRENT_TIMESTAMP,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('phase7-normal','USUARIO_NORMAL','Normal','normal@example.invalid','$2b$12$ggggggggggggggggggggggHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',false,NULL,CURRENT_TIMESTAMP,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "AuthSessionVersion" (id,"userId",version,"updatedAt") VALUES ('phase7-v1','phase7-owner-a',2,CURRENT_TIMESTAMP),('phase7-v2','phase7-owner-b',0,CURRENT_TIMESTAMP),('phase7-v3','phase7-agent-a',1,CURRENT_TIMESTAMP),('phase7-v4','phase7-normal',0,CURRENT_TIMESTAMP);
INSERT INTO "Inmobiliaria" (id,"userId","nombreAgencia",cuit,direccion,"createdAt","updatedAt") VALUES ('phase7-tenant-a','phase7-owner-a','Tenant A','30-70000000-1','Calle A',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('phase7-tenant-b','phase7-owner-b','Tenant B','30-70000000-2','Calle B',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
UPDATE "User" SET "agenciaId"='phase7-tenant-a' WHERE id='phase7-agent-a';
INSERT INTO "Propiedad" (id,"inmobiliariaId","agenteId",titulo,descripcion,estado,tipo,operacion,precio,moneda,direccion,latitud,longitud,"m2Total","m2Cubiertos",ambientes,dormitorios,banos,cocheras,caracteristicas,imagenes,"createdAt","updatedAt") VALUES ('phase7-property-a','phase7-tenant-a','phase7-agent-a','Casa A','Descripción sintética.','DISPONIBLE','Casa','VENTA',12345.67,'USD','Calle A 1',-37.32,-59.13,100,80,3,2,1,1,ARRAY['patio'],'[]'::jsonb,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Contacto" (id,nombre,email,mensaje,"propiedadId",estado,origen,"createdAt") VALUES ('phase7-contact','Contacto','contact@example.invalid','Consulta ficticia','phase7-property-a','NUEVO','PUBLICO',CURRENT_TIMESTAMP);`;
const snapshot=`SELECT count(*)||':'||string_agg(id,',' ORDER BY id)||':'||string_agg("passwordHash",',' ORDER BY id)||':'||string_agg(rol::text,',' ORDER BY id) FROM "User";
SELECT count(*)||':'||string_agg(id,',' ORDER BY id) FROM "Inmobiliaria";
SELECT count(*)||':'||string_agg(id,',' ORDER BY id)||':'||sum(precio)::text FROM "Propiedad";
SELECT count(*)||':'||string_agg(id,',' ORDER BY id) FROM "Contacto";
SELECT count(*)||':'||sum(version)::text FROM "AuthSessionVersion";`;
function upgrade(){createDatabase('phase7_upgrade');applyBeforePhase7('phase7_upgrade');sql('phase7_upgrade',fixture);const before=sql('phase7_upgrade',snapshot).stdout;sql('phase7_upgrade',readFileSync(`${migrationRoot}/${phase7}/preflight.sql`,'utf8'));sql('phase7_upgrade',readFileSync(`${migrationRoot}/${phase7}/migration.sql`,'utf8'));if(sql('phase7_upgrade',snapshot).stdout!==before)throw new Error('Upgrade Phase 7 modificó datos existentes');if(sql('phase7_upgrade','SELECT count(*) FROM "AccountInvitation";').stdout.trim()!=='0')throw new Error('Upgrade creó invitaciones falsas');process.stdout.write('phase7 upgrade: users, hashes, roles, tenants, properties, contacts and versions preserved: ok\n');}
function rollback(port){createDatabase('phase7_rollback');prisma(['migrate','deploy'],url('phase7_rollback',port));sql('phase7_rollback',readFileSync(`${migrationRoot}/${phase7}/rollback.sql`,'utf8'));const state=sql('phase7_rollback',`SELECT count(*) FROM information_schema.tables WHERE table_name='AccountInvitation'; SELECT count(*) FROM information_schema.columns WHERE table_name='SecurityEvent' AND column_name IN ('actorUserId','targetUserId','targetInmobiliariaId'); SELECT count(*) FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='SecurityEventType' AND e.enumlabel='GLOBAL_ADMIN_PROMOTED';`).stdout.trim();if(state!=='0\n0\n0')throw new Error(`Rollback Phase 7 incompleto: ${state}`);process.stdout.write('phase7 rollback: structural rollback verified; backup required after administrative use: ok\n');}
let started=false;try{docker(['run','--detach','--name',container,'-e','POSTGRES_HOST_AUTH_METHOD=trust','-p','127.0.0.1::5432','postgres:17-alpine'],{capture:true});started=true;for(let attempt=0;attempt<40;attempt+=1){if(docker(['exec',container,'pg_isready','-U','postgres'],{allowFailure:true,capture:true}).status===0)break;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,250);}const mapping=docker(['port',container,'5432/tcp'],{capture:true}).stdout.trim();const port=Number(mapping.slice(mapping.lastIndexOf(':')+1));if(integrationOnly){createDatabase('phase7_integration');prisma(['migrate','deploy'],url('phase7_integration',port));integration('phase7_integration',port);process.stdout.write('phase7 PostgreSQL integration: ok\n');}else{empty(port);upgrade();rollback(port);}}finally{if(started)docker(['rm','--force',container],{allowFailure:true,capture:true});}
