import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';
import process from 'node:process';

const root=process.cwd();const migrationRoot=`${root}/database/migrations`;const phase7b='20260806120000_phase7b_inmobiliaria_onboarding';const integrationOnly=process.argv.includes('--integration-only');const container=`tandil-phase7b-${process.pid}-${randomBytes(3).toString('hex')}`;
for(const argument of process.argv.slice(2))if(argument!=='--integration-only')throw new Error(`Argumento no reconocido: ${argument}`);
function run(command,args,options={}){const result=spawnSync(command,args,{cwd:root,encoding:'utf8',env:options.env??process.env,input:options.input,stdio:options.capture?['pipe','pipe','pipe']:['pipe','inherit','inherit']});if(!options.allowFailure&&result.status!==0)throw new Error(`${command} terminó con código ${result.status??'desconocido'}${result.stderr?`: ${result.stderr.trim()}`:''}`);return result;}function docker(args,options={}){return run('docker',args,options);}function sql(database,input,options={}){return docker(['exec','-i',container,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres','-d',database],{input,capture:true,allowFailure:options.allowFailure});}function url(database,port){return `postgresql://postgres@127.0.0.1:${port}/${database}`;}function createDatabase(name){for(let attempt=0;attempt<30;attempt+=1){if(docker(['exec',container,'createdb','-U','postgres',name],{allowFailure:true,capture:true}).status===0)return;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,250);}throw new Error(`No se creó ${name}`);}function prisma(args,databaseUrl,options={}){return run('npx',['prisma',...args],{...options,env:{...process.env,DATABASE_URL:databaseUrl}});}function applyBeforePhase7B(database){for(const name of readdirSync(migrationRoot,{withFileTypes:true}).filter((entry)=>entry.isDirectory()&&entry.name<phase7b).map((entry)=>entry.name).sort())sql(database,readFileSync(`${migrationRoot}/${name}/migration.sql`,'utf8'));}
function environment(databaseUrl){return {...process.env,NODE_ENV:'test',DATABASE_URL:databaseUrl,PHASE7B_DATABASE_URL:databaseUrl,NEXTAUTH_URL:'http://localhost:3000',NEXTAUTH_SECRET:randomBytes(48).toString('base64url'),APP_URL:'http://localhost:3000',AUTH_ENCRYPTION_KEY:randomBytes(32).toString('base64'),RATE_LIMIT_BACKEND:'memory',INVITATION_GEMINI_ENABLED:'false'};}
function integration(database,port){const databaseUrl=url(database,port);run('npx',['tsx','--test','tests/integration/phase-7b-onboarding-postgres.test.ts'],{env:environment(databaseUrl)});}
function empty(port){createDatabase('phase7b_empty');const databaseUrl=url('phase7b_empty',port);prisma(['migrate','deploy'],databaseUrl);const drift=prisma(['migrate','diff','--exit-code','--from-config-datasource','--to-schema','database/schema.prisma'],databaseUrl,{capture:true,allowFailure:true});if(drift.status!==0)throw new Error(`Drift Phase 7B: ${drift.stdout}${drift.stderr}`);const structure=sql('phase7b_empty',`SELECT count(*) FROM information_schema.columns WHERE table_name='AccountInvitation' AND column_name IN ('deliveryStatus','lastDeliveryAttemptAt','sentAt');
SELECT count(*) FROM pg_constraint WHERE conname='AccountInvitation_delivery_check';
SELECT count(*) FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='AccountInvitationDeliveryStatus';
SELECT count(*) FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='SecurityEventType' AND e.enumlabel IN ('ACCOUNT_INVITATION_CREATED','ACCOUNT_INVITATION_SENT','ACCOUNT_INVITATION_RESENT','ACCOUNT_INVITATION_SEND_FAILED');`).stdout.trim();if(structure!=='3\n1\n3\n4')throw new Error(`Estructura Phase 7B inesperada: ${structure}`);integration('phase7b_empty',port);process.stdout.write('phase7b empty: 24 migrations, delivery state, integration and zero drift: ok\n');}
function upgrade(){createDatabase('phase7b_upgrade');applyBeforePhase7B('phase7b_upgrade');sql('phase7b_upgrade',`INSERT INTO "User" (id,rol,nombre,email,"passwordHash","twoFactorEnabled","emailVerifiedAt",activo,"createdAt","updatedAt") VALUES ('p7b-admin','ADMIN','Admin','admin@example.invalid','$2b$12$aaaaaaaaaaaaaaaaaaaaaaBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',false,CURRENT_TIMESTAMP,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('p7b-owner','INMOBILIARIA','Owner','owner@example.invalid','$2b$12$ccccccccccccccccccccccDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',false,NULL,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "AuthSessionVersion" (id,"userId",version,"updatedAt") VALUES ('p7b-v1','p7b-admin',0,CURRENT_TIMESTAMP),('p7b-v2','p7b-owner',0,CURRENT_TIMESTAMP);
INSERT INTO "Inmobiliaria" (id,"userId","nombreAgencia",cuit,direccion,"createdAt","updatedAt") VALUES ('p7b-tenant','p7b-owner','Tenant Preservado','30-71111111-1','Calle Preservada',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "AccountInvitation" (id,"userId","createdById","inmobiliariaId","intendedRole","tokenHash","expiresAt","createdAt") VALUES ('p7b-invite','p7b-owner','p7b-admin','p7b-tenant','INMOBILIARIA',repeat('a',64),CURRENT_TIMESTAMP + interval '24 hours',CURRENT_TIMESTAMP);`);const before=sql('phase7b_upgrade','SELECT count(*) FROM "User"; SELECT count(*) FROM "Inmobiliaria"; SELECT count(*) FROM "AccountInvitation";').stdout;sql('phase7b_upgrade',readFileSync(`${migrationRoot}/${phase7b}/preflight.sql`,'utf8'));sql('phase7b_upgrade',readFileSync(`${migrationRoot}/${phase7b}/migration.sql`,'utf8'));if(sql('phase7b_upgrade','SELECT count(*) FROM "User"; SELECT count(*) FROM "Inmobiliaria"; SELECT count(*) FROM "AccountInvitation";').stdout!==before)throw new Error('Upgrade Phase 7B perdió datos');if(sql('phase7b_upgrade','SELECT "deliveryStatus" FROM "AccountInvitation" WHERE id=\'p7b-invite\';').stdout.trim()!=='PENDING')throw new Error('Invitación anterior no quedó pendiente');process.stdout.write('phase7b upgrade: users, tenants and invitations preserved: ok\n');}
function rollback(port){createDatabase('phase7b_rollback');prisma(['migrate','deploy'],url('phase7b_rollback',port));sql('phase7b_rollback',readFileSync(`${migrationRoot}/${phase7b}/rollback.sql`,'utf8'));const state=sql('phase7b_rollback',`SELECT count(*) FROM information_schema.columns WHERE table_name='AccountInvitation' AND column_name IN ('deliveryStatus','lastDeliveryAttemptAt','sentAt'); SELECT count(*) FROM pg_type WHERE typname='AccountInvitationDeliveryStatus';`).stdout.trim();if(state!=='0\n0')throw new Error(`Rollback Phase 7B incompleto: ${state}`);process.stdout.write('phase7b rollback: delivery structure removed; backup required for enum/audit restoration: ok\n');}
let started=false;try{docker(['run','--detach','--name',container,'-e','POSTGRES_HOST_AUTH_METHOD=trust','-p','127.0.0.1::5432','postgres:17-alpine'],{capture:true});started=true;for(let attempt=0;attempt<40;attempt+=1){if(docker(['exec',container,'pg_isready','-U','postgres'],{allowFailure:true,capture:true}).status===0)break;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,250);}const mapping=docker(['port',container,'5432/tcp'],{capture:true}).stdout.trim();const port=Number(mapping.slice(mapping.lastIndexOf(':')+1));if(integrationOnly){createDatabase('phase7b_integration');prisma(['migrate','deploy'],url('phase7b_integration',port));integration('phase7b_integration',port);process.stdout.write('phase7b PostgreSQL integration: ok\n');}else{empty(port);upgrade();rollback(port);}}finally{if(started)docker(['rm','--force',container],{allowFailure:true,capture:true});}
