-- CreateTable
CREATE TABLE "Propiedad" (
    "id" TEXT NOT NULL,
    "titulo" TEXT NOT NULL,
    "descripcion" TEXT NOT NULL,
    "precio" DOUBLE PRECISION NOT NULL,
    "moneda" TEXT NOT NULL DEFAULT 'USD',
    "tipo" TEXT NOT NULL,
    "operacion" TEXT NOT NULL,
    "latitud" DOUBLE PRECISION NOT NULL,
    "longitud" DOUBLE PRECISION NOT NULL,
    "m2Total" DOUBLE PRECISION NOT NULL,
    "m2Cubierto" DOUBLE PRECISION NOT NULL,
    "m2Semicubierto" DOUBLE PRECISION DEFAULT 0,
    "frenteTerreno" DOUBLE PRECISION,
    "largoTerreno" DOUBLE PRECISION,
    "ambientes" INTEGER NOT NULL,
    "dormitorios" INTEGER NOT NULL,
    "banos" INTEGER NOT NULL,
    "toilettes" INTEGER DEFAULT 0,
    "cocheras" INTEGER DEFAULT 0,
    "tipoCochera" TEXT,
    "plantas" INTEGER NOT NULL DEFAULT 1,
    "antiguedadAnos" INTEGER NOT NULL,
    "ambientesExtra" TEXT[],
    "servicios" TEXT[],
    "comodidades" TEXT[],
    "imagenes" TEXT[],
    "tourVirtualUrl" TEXT,
    "esSustentable" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Propiedad_pkey" PRIMARY KEY ("id")
);
