DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM "AuthSession") OR EXISTS (
    SELECT 1 FROM "SecurityEvent"
    WHERE type::text IN ('SESSION_CREATED','SESSION_REVOKED','OTHER_SESSIONS_REVOKED','ALL_SESSIONS_REVOKED','SESSION_EXPIRED')
  ) THEN
    RAISE EXCEPTION 'PHASE6E_ROLLBACK: restore the pre-migration backup; Phase 6E session data exists';
  END IF;
END $$;

DROP TABLE "AuthSession";

ALTER TYPE "SecurityEventType" RENAME TO "SecurityEventType_phase6e";
CREATE TYPE "SecurityEventType" AS ENUM (
  'REGISTRATION','VERIFICATION_REQUESTED','EMAIL_VERIFIED','LOGIN_SUCCEEDED','LOGIN_FAILED',
  'TWO_FACTOR_CHALLENGE','TWO_FACTOR_ENABLED','RECOVERY_CODE_USED','TWO_FACTOR_DISABLED',
  'PASSWORD_RESET_REQUESTED','PASSWORD_RESET_COMPLETED','PASSWORD_CHANGED','PASSWORD_CHANGE_FAILED',
  'SESSIONS_INVALIDATED','ACCOUNT_DISABLED','SESSION_VERSION_INITIALIZED','SESSION_VERSION_INCREMENTED',
  'PASSWORD_RESET_TOKEN_CREATED','PASSWORD_RESET_TOKEN_CONSUMED','PASSWORD_RESET_TOKENS_INVALIDATED',
  'TOTP_CONFIGURATION_CREATED','TOTP_STEP_REPLAY_REJECTED','TWO_FACTOR_CHALLENGE_CREATED',
  'TWO_FACTOR_CHALLENGE_CONSUMED','TWO_FACTOR_CHALLENGE_INVALIDATED','RECOVERY_CODE_CONSUMED',
  'RECOVERY_CODES_REGENERATED','TWO_FACTOR_SETUP_STARTED','TWO_FACTOR_CHALLENGE_FAILED',
  'TWO_FACTOR_CHALLENGE_COMPLETED','RECOVERY_CODE_LOGIN_SUCCEEDED','RECOVERY_CODE_LOGIN_FAILED'
);
ALTER TABLE "SecurityEvent" ALTER COLUMN type TYPE "SecurityEventType" USING type::text::"SecurityEventType";
DROP TYPE "SecurityEventType_phase6e";
