-- Structural rollback is possible only before Phase 6C audit events exist.
-- Restore a database backup when these events have already been recorded.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM "SecurityEvent"
    WHERE type::text IN ('PASSWORD_RESET_COMPLETED', 'PASSWORD_CHANGE_FAILED')
  ) THEN
    RAISE EXCEPTION 'PHASE6C_ROLLBACK: restore the pre-migration backup; Phase 6C security events exist';
  END IF;
END $$;

ALTER TYPE "SecurityEventType" RENAME TO "SecurityEventType_phase6c";
CREATE TYPE "SecurityEventType" AS ENUM (
  'REGISTRATION',
  'VERIFICATION_REQUESTED',
  'EMAIL_VERIFIED',
  'LOGIN_SUCCEEDED',
  'LOGIN_FAILED',
  'TWO_FACTOR_CHALLENGE',
  'TWO_FACTOR_ENABLED',
  'RECOVERY_CODE_USED',
  'TWO_FACTOR_DISABLED',
  'PASSWORD_RESET_REQUESTED',
  'PASSWORD_CHANGED',
  'SESSIONS_INVALIDATED',
  'ACCOUNT_DISABLED',
  'SESSION_VERSION_INITIALIZED',
  'SESSION_VERSION_INCREMENTED',
  'PASSWORD_RESET_TOKEN_CREATED',
  'PASSWORD_RESET_TOKEN_CONSUMED',
  'PASSWORD_RESET_TOKENS_INVALIDATED',
  'TOTP_CONFIGURATION_CREATED',
  'TOTP_STEP_REPLAY_REJECTED',
  'TWO_FACTOR_CHALLENGE_CREATED',
  'TWO_FACTOR_CHALLENGE_CONSUMED',
  'TWO_FACTOR_CHALLENGE_INVALIDATED',
  'RECOVERY_CODE_CONSUMED',
  'RECOVERY_CODES_REGENERATED'
);
ALTER TABLE "SecurityEvent"
  ALTER COLUMN type TYPE "SecurityEventType"
  USING type::text::"SecurityEventType";
DROP TYPE "SecurityEventType_phase6c";
